/** Frozen projection of Fallow 3.22.0; update only with reviewed certification evidence. */
export const certifiedFallowCapabilities = {
	name: "fallow",
	certifiedVersion: "3.22.0",
	manifestVersion: "1",
	defaultCommand: null,
	outputFormats: ["human","json","sarif","compact","markdown","md","codeclimate","gitlab-codequality","gitlab-code-quality","pr-comment-github","pr-comment-gitlab","review-github","review-gitlab","badge","github-annotations","github-summary"],
	globalFlags: ["--root","--config","--allow-remote-extends","--format","--pretty","--quiet","--no-cache","--threads","--changed-since","--diff-file","--diff-stdin","--churn-file","--max-file-size","--baseline","--baseline-mode","--parent-run","--save-baseline","--production","--no-production","--production-dead-code","--production-health","--production-dupes","--workspace","--changed-workspaces","--group-by","--performance","--explain","--explain-skipped","--summary","--ci","--fail-on-issues","--sarif-file","--output-file","--report-path-prefix","--fail-on-regression","--tolerance","--regression-baseline","--save-regression-baseline","--only","--skip","--dupes-mode","--dupes-near","--dupes-threshold","--dupes-min-tokens","--dupes-min-lines","--dupes-min-occurrences","--dupes-skip-local","--dupes-cross-language","--dupes-ignore-imports","--dupes-no-ignore-imports","--score","--trend","--save-snapshot","--coverage","--coverage-root","--include-entry-exports","--type-aware","--no-type-aware","--type-aware-project","--type-aware-require"],
	commands: {
		"dead-code": ["--unused-files","--unused-exports","--unused-deps","--unused-types","--private-type-leaks","--unused-enum-members","--unused-class-members","--unused-store-members","--unprovided-injects","--unrendered-components","--unused-component-props","--unused-component-emits","--unused-component-inputs","--unused-component-outputs","--unused-svelte-events","--unused-server-actions","--unused-load-data-keys","--unresolved-imports","--unlisted-deps","--duplicate-exports","--circular-deps","--re-export-cycles","--boundary-violations","--policy-violations","--stale-suppressions","--unused-catalog-entries","--empty-catalog-groups","--unresolved-catalog-references","--unused-dependency-overrides","--misconfigured-dependency-overrides","--include-dupes","--trace","--trace-file","--trace-dependency","--impact-closure","--symbol-impact","--top","--file"],
		"watch": ["--no-clear"],
		"type-aware": [],
		"similar-code": ["--threshold","--min-lines","--top","--file"],
		"inspect": ["--file","--symbol","--symbol-chain","--churn"],
		"trace": ["symbol","--callers","--callees","--depth"],
		"fix": ["--dry-run","--yes","--no-create-config"],
		"init": ["--toml","--agents","--hooks","--branch","--decline"],
		"hooks": [],
		"agent": [],
		"ci": [],
		"config-schema": [],
		"plugin-schema": [],
		"plugin-check": [],
		"rule-pack-schema": [],
		"rule-pack": [],
		"guard": ["files"],
		"config": ["--path"],
		"recommend": [],
		"list": ["--entry-points","--files","--plugins","--boundaries","--workspaces"],
		"workspaces": [],
		"dupes": ["--mode","--near","--min-tokens","--min-lines","--min-occurrences","--threshold","--skip-local","--cross-language","--ignore-imports","--no-ignore-imports","--top","--trace"],
		"health": ["--max-cyclomatic","--max-cognitive","--max-crap","--top","--sort","--complexity","--complexity-breakdown","--file-scores","--coverage-gaps","--hotspots","--ownership","--ownership-emails","--targets","--type-coupling","--css","--effort","--score","--min-score","--min-severity","--report-only","--since","--min-commits","--save-snapshot","--trend","--coverage","--coverage-root","--runtime-coverage","--min-invocations-hot","--min-observation-volume","--low-traffic-threshold"],
		"flags": ["--top"],
		"suppressions": ["--file"],
		"explain": ["issue_type"],
		"audit": ["--production-dead-code","--production-health","--production-dupes","--dead-code-baseline","--health-baseline","--dupes-baseline","--max-crap","--coverage","--coverage-root","--no-css","--css-deep","--no-css-deep","--gate","--runtime-coverage","--min-invocations-hot","--gate-marker","--brief","--max-decisions","--walkthrough-guide","--walkthrough-file","--walkthrough","--mark-viewed","--show-cleared","--show-deprioritized"],
		"audit-cache": [],
		"decision-surface": ["--max-decisions"],
		"impact": ["--all","--sort","--limit"],
		"security": ["--runtime-coverage","--min-invocations-hot","--file","--gate","--surface"],
		"report": ["--from"],
		"schema": [],
		"ci-template": [],
		"migrate": ["--toml","--jsonc","--dry-run","--from"],
		"license": [],
		"telemetry": [],
		"coverage": [],
		"setup-hooks": ["--agent","--dry-run","--force","--user","--gitignore-claude","--uninstall"],
		"viz": ["--out","--no-open","--viz-format"],
	},
	issueTypes: [
		["unused-file","dead-code","unused_files"],
		["unused-export","dead-code","unused_exports"],
		["unused-type","dead-code","unused_types"],
		["private-type-leak","dead-code","private_type_leaks"],
		["unused-dependency","dead-code","unused_dependencies"],
		["unused-dev-dependency","dead-code","unused_dev_dependencies"],
		["unused-optional-dependency","dead-code","unused_optional_dependencies"],
		["type-only-dependency","dead-code","type_only_dependencies"],
		["test-only-dependency","dead-code","test_only_dependencies"],
		["dev-dependency-in-production","dead-code","dev_dependencies_in_production"],
		["unused-enum-member","dead-code","unused_enum_members"],
		["unused-class-member","dead-code","unused_class_members"],
		["unused-store-member","dead-code","unused_store_members"],
		["unresolved-import","dead-code","unresolved_imports"],
		["unlisted-dependency","dead-code","unlisted_dependencies"],
		["duplicate-export","dead-code","duplicate_exports"],
		["circular-dependency","dead-code","circular_dependencies"],
		["re-export-cycle","dead-code","re_export_cycles"],
		["boundary-violation","dead-code","boundary_violations"],
		["boundary-coverage","dead-code","boundary_coverage_violations"],
		["boundary-call-violation","dead-code","boundary_call_violations"],
		["policy-violation","dead-code","policy_violations"],
		["stale-suppression","dead-code","stale_suppressions"],
		["missing-suppression-reason","dead-code",null],
		["unused-catalog-entry","dead-code","unused_catalog_entries"],
		["empty-catalog-group","dead-code","empty_catalog_groups"],
		["unresolved-catalog-reference","dead-code","unresolved_catalog_references"],
		["unused-dependency-override","dead-code","unused_dependency_overrides"],
		["misconfigured-dependency-override","dead-code","misconfigured_dependency_overrides"],
		["invalid-client-export","dead-code","invalid_client_exports"],
		["mixed-client-server-barrel","dead-code","mixed_client_server_barrels"],
		["misplaced-directive","dead-code","misplaced_directives"],
		["unprovided-inject","dead-code","unprovided_injects"],
		["unrendered-component","dead-code","unrendered_components"],
		["unused-component-prop","dead-code","unused_component_props"],
		["unused-component-emit","dead-code","unused_component_emits"],
		["unused-component-input","dead-code","unused_component_inputs"],
		["unused-component-output","dead-code","unused_component_outputs"],
		["unused-svelte-event","dead-code","unused_svelte_events"],
		["unused-server-action","dead-code","unused_server_actions"],
		["unused-load-data-key","dead-code","unused_load_data_keys"],
		["prop-drilling","dead-code","prop_drilling_chains"],
		["thin-wrapper","dead-code","thin_wrappers"],
		["duplicate-prop-shape","dead-code","duplicate_prop_shapes"],
		["route-collision","dead-code","route_collisions"],
		["dynamic-segment-name-conflict","dead-code","dynamic_segment_name_conflicts"],
		["high-cyclomatic-complexity","health",null],
		["high-cognitive-complexity","health",null],
		["high-complexity","health",null],
		["high-crap-score","health",null],
		["refactoring-target","health",null],
		["css-token-drift","health",null],
		["css-duplicate-block","health",null],
		["css-selector-complexity","health",null],
		["css-dead-surface","health",null],
		["css-broken-reference","health",null],
		["untested-file","health",null],
		["untested-export","health",null],
		["runtime-safe-to-delete","health",null],
		["runtime-review-required","health",null],
		["runtime-low-traffic","health",null],
		["runtime-coverage-unavailable","health",null],
		["runtime-coverage","health",null],
		["coverage-intelligence-risky-change","health",null],
		["coverage-intelligence-delete","health",null],
		["coverage-intelligence-review","health",null],
		["coverage-intelligence-refactor","health",null],
		["code-duplication","dupes",null],
		["feature-flag","flags",null],
		["tainted-sink","security",null],
		["client-server-leak","security",null],
		["hardcoded-secret","security",null],
		["dangerous-html","security",null],
		["template-escape-bypass","security",null],
		["command-injection","security",null],
		["code-injection","security",null],
		["dynamic-regex","security",null],
		["redos-regex","security",null],
		["resource-amplification","security",null],
		["dynamic-module-load","security",null],
		["sql-injection","security",null],
		["ssrf","security",null],
		["secret-to-network","security",null],
		["path-traversal","security",null],
		["header-injection","security",null],
		["open-redirect","security",null],
		["postmessage-wildcard-origin","security",null],
		["tls-validation-disabled","security",null],
		["cleartext-transport","security",null],
		["electron-unsafe-webpreferences","security",null],
		["world-writable-permission","security",null],
		["insecure-temp-file","security",null],
		["mysql-multiple-statements","security",null],
		["permissive-cors","security",null],
		["insecure-cookie","security",null],
		["mass-assignment","security",null],
		["weak-crypto","security",null],
		["insecure-randomness","security",null],
		["jwt-alg-none","security",null],
		["jwt-verify-missing-algorithms","security",null],
		["deprecated-cipher","security",null],
		["unsafe-buffer-alloc","security",null],
		["unsafe-deserialization","security",null],
		["angular-trusted-html","security",null],
		["nextjs-open-redirect","security",null],
		["dom-document-write","security",null],
		["jquery-html","security",null],
		["route-send-file","security",null],
		["webview-injection","security",null],
		["prototype-pollution","security",null],
		["zip-slip","security",null],
		["nosql-injection","security",null],
		["ssti","security",null],
		["xxe","security",null],
		["secret-pii-log","security",null],
		["xpath-injection","security",null],
		["llm-call-injection","security",null],
	],
	relatedSchemaCommands: ["fallow config-schema","fallow rule-pack-schema","fallow plugin-schema","fallow plugin-check"],
	resourceUris: ["fallow://tools","fallow://issue-types","fallow://explain","fallow://task-matrix","fallow://schema/config","fallow://schema/plugin","fallow://schema/rule-pack","fallow://explain/{issue_type}"],
	reportSchemas: {"combined":"11","dead-code":"9","dupes":"9","health":"11","security":"8","similar-code":"1","runtime-coverage":"2"},
} as const;
